engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
  - "dist/*.js"
exclude_paths:
  - "src/bin.js"
  - "dist/bin.js"
